const chat=document.getElementById('chat'),welcome=document.getElementById('welcome'),form=document.getElementById('composer'),input=document.getElementById('prompt');
const cfg=window.BUNVIX_CONFIG||{};const SUPABASE_URL=cfg.SUPABASE_URL||'';const SUPABASE_ANON_KEY=cfg.SUPABASE_ANON_KEY||'';const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);const FUNCTION_URL=`${SUPABASE_URL}/functions/v1/chat`;let session=null;let conversationId=null;let history=[];
function addMessage(text,kind){const el=document.createElement('div');el.className=`message ${kind}`;el.textContent=text;chat.appendChild(el);chat.scrollTop=chat.scrollHeight;return el}
async function ensureSession(){if(!sb)throw new Error('Supabase is not configured.');const {data}=await sb.auth.getSession();if(data.session){session=data.session;return session}const {data:d,error}=await sb.auth.signInAnonymously();if(error)throw error;session=d.session;return session}
async function createConversation(title='New chat'){const s=await ensureSession();const {data,error}=await sb.from('conversations').insert({user_id:s.user.id,title}).select('id').single();if(error)throw error;conversationId=data.id;return data.id}
async function saveMessage(role,content){const s=await ensureSession();if(!conversationId)await createConversation(role==='user'?content.slice(0,60):'New chat');const {error}=await sb.from('messages').insert({conversation_id:conversationId,user_id:s.user.id,role,content});if(error)throw error;if(role==='user'){await sb.from('conversations').update({title:content.slice(0,60)}).eq('id',conversationId)}}
async function respond(text){const el=addMessage('BUNVIX is thinking…','bot typing');try{await ensureSession();await saveMessage('user',text);const r=await fetch(FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_ANON_KEY,'Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({message:text,history})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');history.push({role:'user',text},{role:'assistant',text:data.answer});await saveMessage('assistant',data.answer);el.classList.remove('typing');el.textContent=data.answer}catch(e){el.classList.remove('typing');el.textContent=`BUNVIX couldn't respond: ${e.message}`}}
form.addEventListener('submit',e=>{e.preventDefault();const text=input.value.trim();if(!text)return;if(welcome)welcome.remove();addMessage(text,'user');input.value='';input.style.height='auto';respond(text)});
input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,150)+'px'});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.prompt;form.requestSubmit()}));document.getElementById('clear').addEventListener('click',()=>{history=[];conversationId=null;location.reload()});document.getElementById('newChat').addEventListener('click',()=>{history=[];conversationId=null;location.reload()});document.getElementById('theme').addEventListener('click',()=>document.body.classList.toggle('light'));document.getElementById('menu').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));
