const chat=document.getElementById('chat'),welcome=document.getElementById('welcome'),form=document.getElementById('composer'),input=document.getElementById('prompt');
const cfg=window.TUBXA_CONFIG||{};const SUPABASE_URL=cfg.SUPABASE_URL||'';const SUPABASE_ANON_KEY=cfg.SUPABASE_ANON_KEY||'';const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);const FUNCTION_URL=`${SUPABASE_URL}/functions/v1/chat`;let session=null,conversationId=null,history=[];
function addMessage(text,kind){const el=document.createElement('div');el.className=`message ${kind}`;el.textContent=text;chat.appendChild(el);chat.scrollTop=chat.scrollHeight;return el}
async function ensureSession(){if(!sb)throw new Error('Supabase is not configured.');const {data}=await sb.auth.getSession();if(data.session){session=data.session;return session}const {data:d,error}=await sb.auth.signInAnonymously();if(error)throw error;session=d.session;return session}
async function loadHistory(){try{const s=await ensureSession();const {data,error}=await sb.from('conversations').select('id,title,updated_at').eq('user_id',s.user.id).order('updated_at',{ascending:false}).limit(30);if(error)throw error;let old=document.getElementById('history');if(!old){old=document.createElement('div');old.id='history';old.className='history';document.getElementById('sidebar').insertBefore(old,document.querySelector('.bottom'));}old.innerHTML='<p class="label">RECENT CHATS</p>';(data||[]).forEach(c=>{const b=document.createElement('button');b.className='nav history-item';b.textContent='▱ '+(c.title||'New chat');b.title=c.title||'New chat';b.onclick=()=>openConversation(c.id);old.appendChild(b)});}catch(e){console.warn('History load failed',e)}}
async function openConversation(id){const s=await ensureSession();const {data,error}=await sb.from('messages').select('role,content,created_at').eq('conversation_id',id).eq('user_id',s.user.id).order('created_at',{ascending:true});if(error){alert(error.message);return}conversationId=id;history=(data||[]).map(m=>({role:m.role,text:m.content}));chat.innerHTML='';history.forEach(m=>addMessage(m.text,m.role==='user'?'user':'bot'));document.getElementById('sidebar').classList.remove('open')}
async function createConversation(title='New chat'){const s=await ensureSession();const {data,error}=await sb.from('conversations').insert({user_id:s.user.id,title}).select('id').single();if(error)throw error;conversationId=data.id;return data.id}
async function saveMessage(role,content){const s=await ensureSession();if(!conversationId)await createConversation(role==='user'?content.slice(0,60):'New chat');const {error}=await sb.from('messages').insert({conversation_id:conversationId,user_id:s.user.id,role,content});if(error)throw error;if(role==='user')await sb.from('conversations').update({title:content.slice(0,60)}).eq('id',conversationId)}
async function respond(text){const el=addMessage('TUBXA is thinking…','bot typing');try{await ensureSession();await saveMessage('user',text);const r=await fetch(FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_ANON_KEY,'Authorization':`Bearer ${session.access_token}`},body:JSON.stringify({message:text,history})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');history.push({role:'user',text},{role:'assistant',text:data.answer});await saveMessage('assistant',data.answer);el.classList.remove('typing');el.textContent=data.answer;await loadHistory()}catch(e){el.classList.remove('typing');el.textContent=`TUBXA couldn't respond: ${e.message}`}}
form.addEventListener('submit',e=>{e.preventDefault();const text=input.value.trim();if(!text)return;if(welcome)welcome.remove();addMessage(text,'user');input.value='';input.style.height='auto';respond(text)});
input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,150)+'px'});document.querySelectorAll('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{input.value=b.dataset.prompt;form.requestSubmit()}));document.getElementById('clear').addEventListener('click',()=>{history=[];conversationId=null;location.reload()});document.getElementById('newChat').addEventListener('click',()=>{history=[];conversationId=null;chat.innerHTML='';if(welcome)chat.appendChild(welcome);});document.getElementById('theme').addEventListener('click',()=>document.body.classList.toggle('light'));document.getElementById('menu').addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));ensureSession().then(loadHistory).catch(console.warn);
